<a href="https://colab.research.google.com/github/prijal-matc/takeovds41/blob/main/ANN_Churn_Modelling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
url = '/content/Churn_Modelling 2.csv'
df = pd.read_csv(url)
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [3]:
df.head(3)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1

In [4]:
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [5]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

**Label Encoding the "Gender" column**

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

**OneHotEncoder on "Geography" column**

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

**Splitting the dataset into the Training set and Test set**

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

**Feature Scaling**

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

**Artificial Neural Network**

**Building ANN**

**Initialization of ANN**

In [13]:
import tensorflow as tf
ann = tf.keras.models.Sequential()

**Adding First Hidden Layer**

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

**Adding Second Hidden Layer**

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

**Third Hidden Layer**

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [18]:
ann.fit(X_train, y_train, batch_size=32, epochs=75)

Epoch 1/75
250/250 [==============================] - 4s 3ms/step - loss: 0.5166 - accuracy: 0.7735
Epoch 2/75
250/250 [==============================] - 1s 3ms/step - loss: 0.4643 - accuracy: 0.7960
Epoch 3/75
250/250 [==============================] - 1s 3ms/step - loss: 0.4467 - accuracy: 0.7968
Epoch 4/75
250/250 [==============================] - 1s 3ms/step - loss: 0.4302 - accuracy: 0.8025
Epoch 5/75
250/250 [==============================] - 1s 3ms/step - loss: 0.4104 - accuracy: 0.8110
Epoch 6/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3919 - accuracy: 0.8154
Epoch 7/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3779 - accuracy: 0.8255
Epoch 8/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3696 - accuracy: 0.8486
Epoch 9/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3639 - accuracy: 0.8537
Epoch 10/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3603 - accuracy: 0.8544
Epoch 11/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3573 - accuracy: 0.8553
Epoch 12/75
250/250 [==============================] - 1s 4ms/step - loss: 0.3547 - accuracy: 0.8569
Epoch 13/75
250/250 [==============================] - 1s 4ms/step - loss: 0.3530 - accuracy: 0.8589
Epoch 14/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3511 - accuracy: 0.8589
Epoch 15/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3495 - accuracy: 0.8589
Epoch 16/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3481 - accuracy: 0.8601
Epoch 17/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3470 - accuracy: 0.8589
Epoch 18/75
250/250 [==============================] - 1s 4ms/step - loss: 0.3457 - accuracy: 0.8605
Epoch 19/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3448 - accuracy: 0.8604
Epoch 20/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3438 - accuracy: 0.8586
Epoch 21/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3431 - accuracy: 0.8600
Epoch 22/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3425 - accuracy: 0.8597
Epoch 23/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3420 - accuracy: 0.8609
Epoch 24/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3415 - accuracy: 0.8609
Epoch 25/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3412 - accuracy: 0.8618
Epoch 26/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3411 - accuracy: 0.8597
Epoch 27/75
250/250 [==============================] - 1s 4ms/step - loss: 0.3406 - accuracy: 0.8608
Epoch 28/75
250/250 [==============================] - 1s 4ms/step - loss: 0.3400 - accuracy: 0.8621
Epoch 29/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3396 - accuracy: 0.8601
Epoch 30/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3396 - accuracy: 0.8618
Epoch 31/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3392 - accuracy: 0.8611
Epoch 32/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3390 - accuracy: 0.8608
Epoch 33/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3386 - accuracy: 0.8615
Epoch 34/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3383 - accuracy: 0.8633
Epoch 35/75
250/250 [==============================] - 1s 4ms/step - loss: 0.3376 - accuracy: 0.8622
Epoch 36/75
250/250 [==============================] - 1s 6ms/step - loss: 0.3381 - accuracy: 0.8615
Epoch 37/75
250/250 [==============================] - 1s 5ms/step - loss: 0.3377 - accuracy: 0.8614
Epoch 38/75
250/250 [==============================] - 1s 6ms/step - loss: 0.3378 - accuracy: 0.8610
Epoch 39/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3375 - accuracy: 0.8627
Epoch 40/75
250/250 [==============================] - 1s 4ms/step - loss: 0.3372 - accuracy: 0.8618
Epoch 41/75
250/250 [==============================] - 1s 4ms/step - loss: 0.3371 - accuracy: 0.8615
Epoch 42/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3370 - accuracy: 0.8635
Epoch 43/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3368 - accuracy: 0.8614
Epoch 44/75
250/250 [==============================] - 1s 5ms/step - loss: 0.3366 - accuracy: 0.8620
Epoch 45/75
250/250 [==============================] - 1s 5ms/step - loss: 0.3365 - accuracy: 0.8629
Epoch 46/75
250/250 [==============================] - 1s 4ms/step - loss: 0.3361 - accuracy: 0.8634
Epoch 47/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3359 - accuracy: 0.8621
Epoch 48/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3363 - accuracy: 0.8633
Epoch 49/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3360 - accuracy: 0.8634
Epoch 50/75
250/250 [==============================] - 1s 5ms/step - loss: 0.3358 - accuracy: 0.8634
Epoch 51/75
250/250 [==============================] - 1s 5ms/step - loss: 0.3356 - accuracy: 0.8625
Epoch 52/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3355 - accuracy: 0.8610
Epoch 53/75
250/250 [==============================] - 1s 4ms/step - loss: 0.3355 - accuracy: 0.8625
Epoch 54/75
250/250 [==============================] - 1s 4ms/step - loss: 0.3353 - accuracy: 0.8614
Epoch 55/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3354 - accuracy: 0.8619
Epoch 56/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3351 - accuracy: 0.8606
Epoch 57/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3345 - accuracy: 0.8633
Epoch 58/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3350 - accuracy: 0.8620
Epoch 59/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3347 - accuracy: 0.8621
Epoch 60/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3348 - accuracy: 0.8621
Epoch 61/75
250/250 [==============================] - 1s 4ms/step - loss: 0.3344 - accuracy: 0.8635
Epoch 62/75
250/250 [==============================] - 1s 5ms/step - loss: 0.3343 - accuracy: 0.8618
Epoch 63/75
250/250 [==============================] - 1s 4ms/step - loss: 0.3343 - accuracy: 0.8627
Epoch 64/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3344 - accuracy: 0.8612
Epoch 65/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3340 - accuracy: 0.8626
Epoch 66/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3337 - accuracy: 0.8633
Epoch 67/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3341 - accuracy: 0.8641
Epoch 68/75
250/250 [==============================] - 1s 4ms/step - loss: 0.3339 - accuracy: 0.8625
Epoch 69/75
250/250 [==============================] - 1s 4ms/step - loss: 0.3336 - accuracy: 0.8621
Epoch 70/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3332 - accuracy: 0.8639
Epoch 71/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3336 - accuracy: 0.8625
Epoch 72/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3333 - accuracy: 0.8627
Epoch 73/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3334 - accuracy: 0.8618
Epoch 74/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3332 - accuracy: 0.8635
Epoch 75/75
250/250 [==============================] - 1s 3ms/step - loss: 0.3328 - accuracy: 0.8641

In [19]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 127ms/step
[[False]]

In [20]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 160000, 2, 1, 1, 150000]])) > 0.5)

1/1 [==============================] - 0s 17ms/step
[[False]]

In [23]:
print(ann.predict(sc.transform([[1, 0, 1, 609, 1, 42, 1, 160000, 1, 1, 1, 150000]])) > 0.5)

1/1 [==============================] - 0s 19ms/step
[[False]]